### ISSUE TITLE
loss of functionality

### ISSUE THREAD

**Issue by dirtycache** [job/irrexplorer#62]
all queries return "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by job** [comment]
i restarted the app, it appears there many people hammering the service, reducing the reliability... :(

version 2 will not have these issues but is in development

**Comment by dirtycache** [comment]
Thanks, Job!

**Comment by dirtycache** [comment]
Same problem still after restart :(

**Comment by job** [comment]
it appears to work for me, what is the search query you are entering?

**Comment by dirtycache** [comment]
Ah yes it appears functional now, perhaps I was just impatient.  The large pink rectangle advising that the request cannot be completed still presents, though.

**Comment by job** [comment]
what url are you looking at?

**Comment by dirtycache** [comment]
http://irrexplorer.nlnog.net/search/AS16970 is one example, I haven't found a URL yet where the rectangle isn't showing up.

**Comment by job** [comment]
ah....

```
[2021-02-04 00:58:57,523] ERROR in app: Exception on /json/as_prefixes/16970 [GET]
Traceback (most recent call last):
  File "/home/irrexplorer/irrexplorer/.venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irrexplorer/irrexplorer/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irrexplorer/irrexplorer/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/irrexplorer/irrexplorer/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irrexplorer/irrexplorer/.venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/irrexplorer/irrexplorer/irrexplorer/www.py", line 165, in as_prefixes
    data = report.as_prefixes(pgdb, int(as_number))
  File "/home/irrexplorer/irrexplorer/irrexplorer/report.py", line 246, in as_prefixes
    prefixes = pgdb.query_as(as_number)
  File "/home/irrexplorer/irrexplorer/irrexplorer/sqldb.py", line 83, in query_as
    return self._execute_fetchall(query, (asn,))
  File "/home/irrexplorer/irrexplorer/irrexplorer/sqldb.py", line 53, in _execute_fetchall
    cur.execute(query, args)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

the website does multiple HTTP requests, and one of the requests lands on a broken worker

**Comment by job** [comment]
plz try again!

**Comment by dirtycache** [comment]
Looks great now.  Thank you again, Job!
