### ISSUE TITLE
Flash/jinja form error on request

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#9]
- Running on http://0.0.0.0:5000/
  sleeping 300 seconds before reconnecting to rr.ntt.net (LEVEL3)
  127.0.0.1 - - [15/May/2015 12:51:16] "GET / HTTP/1.1" 500 -
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/htj/src/irrexplorer/irrexplorer.py", line 478, in index_old
  
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/htj/src/irrexplorer/templates/index.html", line 4, in top-level template code
    {% import "bootstrap/utils.html" as util %}
  File "/home/htj/src/irrexplorer/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/htj/src/irrexplorer/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/htj/src/irrexplorer/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/htj/src/irrexplorer/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/htj/src/irrexplorer/templates/index.html", line 44, in block "content"
    {{ wtf.quick_form(form, form_type='inline', button_map={'submit_button': 'primary'}) }}
  File "/home/htj/src/irrexplorer/flask_bootstrap/templates/bootstrap/wtf.html", line 154, in template
    {{ form.hidden_tag() }}
  UndefinedError: '__main__.InputForm object' has no attribute 'hidden_tag'

Do I need something special here?

**Comment by htj** [comment]
changing the line in wtf.html to

  {{ form.hidden_tag }}

Seems to do the trick.

**Comment by htj** [comment]
Well, then I get this thing:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/htj/src/irrexplorer/irrexplorer.py", line 482, in index_old
    int(data)
TypeError: int() argument must be a string or a number, not 'NoneType'

I cannot seem to get the input data to appear at all, after prodding this for a while :-/

**Comment by job** [comment]
Do you still have this issue? How can I replicate it?

**Comment by htj** [comment]
Hi. Yeah, I am still seeing the issues. Been tracking them down a bit. Some of this may be due to version differences in various flask stuff, but the front page was never possible to use for me. I also has some text shown on the front page, but i fixed that in flask bootstrap with this:

--- wtf.html_ORG    2015-06-19 11:46:53.842421164 +0200
+++ wtf.html    2015-06-19 11:46:27.174421759 +0200
@@ -151,7 +151,7 @@
   {%- if enctype %} enctype="{{enctype}}"{% endif -%}
   {%- if role %} role="{{role}}"{% endif -%}

> -  {{ form.hidden_tag }}
> -  {{ form.hidden_tag() }}
>   {{ form_errors(form, hiddens='only') }}

   {%- for field in form %}

**Comment by htj** [comment]
The above seem fixed in flask_bootstrap 3.3.5.1 (I've been on 3.3.4.1)

**Comment by job** [comment]
production environment:

```
root@irrexplorer:/home/irrexplorer/irrexplorer# grep -r form.hidden_tag .
./.venv/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/wtf.html:  {{ form.hidden_tag() }}

(.venv)root@irrexplorer:/home/irrexplorer/irrexplorer# pip freeze | grep Flask-Bootstrap
Flask-Bootstrap==3.3.2.1
```

**Comment by htj** [comment]
Closing this thing. Haven't seen in since software upgrade.
